### ISSUE TITLE
Can/Should this package be used in combination with general.el?

### ISSUE THREAD

**Issue by dylanjm** [noctuid/annalist.el#3]
It seems your other package `general.el` already provides a function to view bindings in table format. It also looks like general doesn't `(require 'annalist)`. Is there any benefit to using this packages in combination?

**Comment by noctuid** [comment]
General will switch over to using it (for hooks, advice, and settings as well). I have a local branch where the switch for keybindings that is half finished, but I haven't had the time to update everything yet.

**Comment by dylanjm** [comment]
Ahh I see. Thank you.
